INSERT INTO product(code, name, description, image_url, price)
VALUES ('P100', 'Jogos Vorazes', 'Vencer fará de você uma celebridade. Perder significa morte certa...',
        'https://images.gr-assets.com/books/1447303603l/2767052.jpg', 34.0),
       ('P101', 'O Sol é para Todos',
        'O inesquecível romance sobre a infância em uma pacata cidade do sul dos EUA e a crise de consciência que a abalou...',
        'https://images.gr-assets.com/books/1361975680l/2657.jpg', 45.40),
       ('P102', 'As Crônicas de Nárnia',
        'Jornadas até o fim do mundo, criaturas fantásticas e batalhas épicas entre o bem e o mal — o que mais um leitor poderia desejar em um único livro?',
        'https://images.gr-assets.com/books/1449868701l/11127.jpg', 44.50),
       ('P103', 'E o Vento Levou',
        'E o Vento Levou é um romance escrito por Margaret Mitchell, publicado pela primeira vez em 1936.',
        'https://images.gr-assets.com/books/1328025229l/18405.jpg', 44.50),
       ('P104', 'A Culpa é das Estrelas',
        'Apesar do milagre médico que reduziu seu tumor e lhe deu alguns anos a mais, Hazel sempre foi considerada terminal, seu destino selado desde o diagnóstico.',
        'https://images.gr-assets.com/books/1360206420l/11870085.jpg', 14.50),
       ('P105', 'A Árvore Generosa', 'Era uma vez uma árvore... e ela amava um menininho.',
        'https://images.gr-assets.com/books/1174210942l/370493.jpg', 32.0),
       ('P106', 'O Código Da Vinci',
        'Um código engenhoso escondido nas obras de Leonardo da Vinci. Uma corrida desesperada pelas catedrais e castelos da Europa.',
        'https://images.gr-assets.com/books/1303252999l/968.jpg', 14.50),
       ('P107', 'O Alquimista',
        'A obra-prima de Paulo Coelho conta a história mística de Santiago, um jovem pastor andaluz que sonha em viajar em busca de um tesouro.',
        'https://images.gr-assets.com/books/1483412266l/865.jpg', 12.0),
       ('P108', 'A Teia de Charlotte',
        'Este adorado livro de E. B. White, autor de "Stuart Little" e "A Trombeta do Cisne", é um clássico da literatura infantil.',
        'https://images.gr-assets.com/books/1439632243l/24178.jpg', 14.0),
       ('P109', 'O Pequeno Príncipe',
        'Alegoria moral e autobiografia espiritual, "O Pequeno Príncipe" é o livro mais traduzido da língua francesa.',
        'https://images.gr-assets.com/books/1367545443l/157993.jpg', 16.50),
       ('P110', 'A Cidade do Sol',
        'A Cidade do Sol é uma história emocionante ambientada nos últimos trinta anos de eventos turbulentos no Afeganistão — da invasão soviética ao regime Talibã e à reconstrução pós-Talibã.',
        'https://images.gr-assets.com/books/1345958969l/128029.jpg', 15.50),
       ('P111', 'A Guerra dos Tronos',
        'Este é o primeiro volume do magnífico ciclo de romances de George R. R. Martin, que inclui "A Fúria dos Reis" e "A Tormenta de Espadas".',
        'https://images.gr-assets.com/books/1436732693l/13496.jpg', 32.0),
       ('P112', 'A Menina que Roubava Livros',
        'Alemanha nazista. O país prende a respiração. A morte nunca esteve tão ocupada — e ainda estará mais. Ao lado do túmulo do irmão, a vida de Liesel muda ao encontrar um objeto parcialmente escondido na neve.',
        'https://images.gr-assets.com/books/1522157426l/19063.jpg', 30.0),
       ('P113', 'Um Estranho no Ninho',
        'A tirânica Enfermeira Ratched comanda sua ala em um hospital psiquiátrico no Oregon com uma rotina rígida e inflexível, sem oposição dos pacientes, que permanecem apáticos sob medicação e ameaças de eletrochoque.',
        'https://images.gr-assets.com/books/1516211014l/332613.jpg', 23.0),
       ('P114', 'Cinquenta Tons de Cinza',
        'Quando a estudante de literatura Anastasia Steele vai entrevistar o jovem empresário Christian Grey, ela encontra um homem bonito, brilhante e intimidador.',
        'https://images.gr-assets.com/books/1385207843l/10818853.jpg', 27.0);
